"""migration

Revision ID: 2aea840f953e
Revises: 60eb38165020
Create Date: 2023-12-14 10:27:53.073824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aea840f953e'
down_revision: Union[str, None] = '60eb38165020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bidder', 'id_user',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bidder', 'id_user',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
