"""mirgation

Revision ID: 407c53ea6a80
Revises: 2aea840f953e
Create Date: 2023-12-14 18:11:11.914891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '407c53ea6a80'
down_revision: Union[str, None] = '2aea840f953e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bidder', 'id_dog',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bidder', 'id_dog',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
